export const GET_BLOG_LIST = 'GET_USER_LIST';
export const UPDATE_LIMIT = 'UPDATE_LIMIT';
export const UPDATE_TOTAL_BLOG_COUNT = 'UPDATE_TOTAL_BLOG_COUNT';
export const GET_SELECTED_BLOG = 'GET_SELECTED_BLOG';
export const SET_AUTHOR_FILTER = 'SET_AUTHOR_FILTER';
export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const SET_SORT_BY = 'SET_SORT_BY';