export const GET_BLOG_LIST = 'GET_USER_LIST';
export const UPDATE_LIMIT = 'UPDATE_LIMIT';
export const UPDATE_TOTAL_BLOG_COUNT = 'UPDATE_TOTAL_BLOG_COUNT';
export const GET_SELECTED_BLOG = 'GET_SELECTED_BLOG';